### PR TITLE
ci: split CI workflow and add ruff format

### PR DESCRIPTION
**Pull request by yasuhito**
## ✍ Description
Split ci.yaml into three separate files for better organization:

- mypy.yaml
- ruff.yaml
- test.yaml

Also added ruff format command in addition to ruff check in ruff.yaml.
This change makes it easier to manage each CI task and simplifies future maintenance.

### CODE REVIEW

**Review by snuffkin — CHANGES_REQUESTED** [review]
Tranqu's ci flow is small, so it's harder to manage if the files are split up.
I think it's a good idea to add ruff format, so I'd like to keep the files as one.

**Comment by yasuhito** [comment]
I still believe there are several advantages to splitting the CI workflows:

**Faster Execution through Parallelization**
- Each check (ruff, mypy, pytest) can run in parallel, reducing overall execution time
- This becomes particularly beneficial as tests grow in number

**Efficient Error Identification**
- When checks run independently, you can identify all issues at once if multiple problems exist
- For example, even if ruff fails, you can still see errors from mypy and pytest simultaneously
- This reduces the cycle of fix → push → CI error → fix...

**Improved Maintainability**
- Managing each check's configuration in separate files makes the intent clearer
- Change history becomes more transparent for each type of check
- Makes it easier to add new checks or remove existing ones

**Efficient Re-runs**
- If a specific check fails, you can re-run just that workflow
- No need to run all checks every time, leading to more efficient use of CI resources

While the project may be small now, these advantages are significant when considering future scalability.

**Comment by snuffkin** [comment]
Tranqu is currently a small product, so if any problems arise in the future, we would like to consider splitting the files.
Splitting the files will increase duplicate codes. This will make it more difficult to manage.
Looking at the actual execution time for Tranqu's workflow, it is around 30s - 50s, so even if we run it in parallel now, the effect will be small.

**Comment by yasuhito** [comment]
Thank you for your detailed explanation. While I still see value in workflow separation for error identification and maintainability beyond just execution time, I understand your point about the current scale of Tranqu and the potential overhead from duplicate code.

Let's keep it as a single workflow file for now. We can always revisit this discussion when Tranqu grows, and the benefits of parallel execution become more significant.

I'll update the PR to consolidate the workflows into a single file while adding the ruff format check.

**Review by snuffkin — APPROVED** [review]
LGTM!

**Pull request merged**
